### ISSUE TITLE
Function show_spectrogram for mp3 file extension

### ISSUE THREAD

**Issue by zeraye** [zeraye/rege#4]
Currently `show_spectrogram` function works only with .wav files. We should consider improving this function to handle .mp3 files. Function should recognize if file has mp3 extension and look for decoder.

After such an improvement we can work both on .wav and .mp3 files.

**Comment by Patonymous** [comment]
Fortunately, Librosa's `load` function is written in such a way, that when reading a file fails it will automatically check for other registered decoders. All we need to do is provide one. I think the easiest solution is to download a decoder like ffmpeg (found here: [https://www.gyan.dev/ffmpeg/builds/](url)) and add its /bin directory to system's Path variable. I believe that no changes in the script itself need to made (not even an import).

**Comment by zeraye** [comment]
As far as I know, we will work only with .wav files. When we start working with .mp3 we will open new issue. Closing
