### ISSUE TITLE
"voice-synthesis" tag

### ISSUE THREAD

**Issue by Patonymous** [zeraye/rege#5]
Why is our project tag with "voice-synthesis" when we don't actually synthesize any voice? We just analyze it. I think it should be changed. Also I don't know how to do it. Pls someone help.
![image](https://user-images.githubusercontent.com/100200489/158081201-d8fb7494-042b-40fc-b197-9b5758f4f77f.png)

**Comment by zeraye** [comment]
According to https://www.merriam-webster.com/dictionary/synthesis, synthesis means deductive reasoning. I think that is what we are working on. Based on the data read from the audio files, we analyse them and deduce the gender of the author of the voice.

**Comment by zeraye** [comment]
I'm not sure you can change it. Me as an owner has this additional button (top right)
![image](https://user-images.githubusercontent.com/53649257/158084603-36d8b241-8ab2-4b61-accb-17bcbd31ac73.png)

**Comment by zeraye** [comment]
Tag don't fit the subject of this repo.
